import type { Metadata } from "next";
import "./globals.css";
import { MartianMono } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={MartianMono.variable}>
        <div className="layout-1">
          <main role="main">{children}</main>
        </div>
      </body>
    </html>
  );
}
